### PR TITLE
Pre-release v3.0.0-B0203

### PR DESCRIPTION
**Pull request by BernieWhite**
## PR Summary

What's changed since pre-release v3.0.0-B0198:

- New features:
  - **Breaking change**: Simplify handling of inputs from files using emitters by @BernieWhite.
    [#1179](https://github.com/microsoft/PSRule/issues/1179)
    - Files are automatically read from input paths and emitted as objects to the pipeline.
    - Emitter interface can be used to implement custom file readers and expansion of custom file types.
    - The `File` and `Detect` input formats are no longer required and have been removed.
    - Processing files and objects with rules is no longer recommended, and disabled by default.
    - The `Input.FileObjects` can be set to `true` to enable processing of files as objects with rules.
- Engineering:
  - Bump Microsoft.NET.Test.Sdk to v17.10.0.
    [#1826](https://github.com/microsoft/PSRule/pull/1826)
- Bug fixes:
  - Fixed reason reported for `startsWith` by @BernieWhite.
    [#1818](https://github.com/microsoft/PSRule/issues/1818)
  - Fixes CSV output of multiple lines by @BernieWhite.
    [#1627](https://github.com/microsoft/PSRule/issues/1627)

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**

### CODE REVIEW

**Comment by lassehastrup** [comment]
My apologies, @BernieWhite , you're correct.

However, now that have imported the correct version I receive this:

image

In the release notes it states:

`
The File and Detect input formats are no longer required and have been removed.
`

After out commenting the: Input.File

image

It can read the yaml option file successfully without errors.

But It doesn't process any of the rules:

image

I have attempted with the Input.FileObjects set to true, but this doesn't change anything.

Any hints?

**Comment by BernieWhite** [comment]
Hi @lassehastrup. 

PSRule for Azure will be updated to support the new emitters interface but until PSRule v3 is releases as stable, setting `Input.FileObjects` to `true` is required. Outside of that it should work.

Are you able to share a other options either set via `ps-rule.yaml` or on the command line in-case there is an edge case that doesn't quite work in the pre-release. Feel free to sanitize any suppressions as required.

**Comment by BernieWhite** [comment]
@lassehastrup Thanks. A quick one that I can see is the case for `FileObjects` should be `fileObjects` for the YAML syntax, because the keys are case-sensitive.

See: https://microsoft.github.io/PSRule/v3/concepts/PSRule/en-US/about_PSRule_Options/#inputfileobjects

But I'll look at trying to reproduce that later today.

**Comment by lassehastrup** [comment]
@BernieWhite , appreciate it. That did the trick.

Everything works as expected now, and the 'reason' is now outputted correct.

image

Thank you very much, Bernie!

**Pull request merged**
